#!/usr/bin/env node
/**
 * Pulls Shane's posted LinkedIn posts from Ordinal into notes/_data/, the
 * notes-side equivalent of sync-beehiiv.mjs. tools/build-notes.mjs then turns
 * that data into /notes and the homepage "Lately" strip.
 *
 *   ORDINAL_API_KEY=... node tools/sync-ordinal.mjs
 *
 * Writes:
 *   notes/_data/posts.json     { id, title, date, labels, images, copy }[]
 *   notes/_data/linkedin.json  { <id>: { urn, likes, comments } }
 *   images/notes/<assetId>.jpg (downloaded once, Bearer-authed)
 *
 * Source of truth is Ordinal, so posts.json is regenerated in full each run —
 * an edited or deleted post on Ordinal is reflected here on the next sync.
 * Runs in .github/workflows/sync-notes.yml on a cron; a run that changes
 * nothing exits without a commit.
 *
 * API: https://docs.tryordinal.com/api  (Bearer auth, 100 req/min/workspace)
 *   GET /posts                                   list posts
 *   GET /analytics/linkedin/{profileId}/posts    engagement + permalink
 *   GET <asset.url>                              media (redirects to signed URL)
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const DATA = resolve(ROOT, 'notes/_data');
const IMG = resolve(ROOT, 'images/notes');

const BASE = 'https://app.tryordinal.com/api/v1';
// Shane's personal LinkedIn profile in the Ordinal workspace. Stable; the
// notes archive mirrors this profile only (not the Certainly company page).
const LINKEDIN_PROFILE_ID = 'e520de3c-1516-480b-8332-ec650c342f9f';
// Nothing on Ordinal predates this; it bounds the analytics window.
const SINCE = '2026-06-01T00:00:00.000Z';

const KEY = process.env.ORDINAL_API_KEY;
if (!KEY) {
  console.error('ORDINAL_API_KEY is not set.');
  process.exit(1);
}

const auth = { Authorization: `Bearer ${KEY}` };

async function api(path) {
  const res = await fetch(`${BASE}${path}`, { headers: auth });
  if (!res.ok) throw new Error(`GET ${path} -> ${res.status} ${await res.text()}`);
  return res.json();
}

// --- 1. Posts (paginated, newest first) -----------------------------------
const rawPosts = [];
let cursor = null;
do {
  const q = new URLSearchParams({
    channel: 'LinkedIn',
    linkedInProfileId: LINKEDIN_PROFILE_ID,
    status: 'Posted',
    sortBy: 'publishAt',
    sortOrder: 'desc',
    limit: '100',
  });
  if (cursor) q.set('cursor', cursor);
  const page = await api(`/posts?${q}`);
  rawPosts.push(...(page.posts || []));
  cursor = page.hasMore ? page.nextCursor : null;
} while (cursor);

const posts = rawPosts.map((p) => ({
  id: p.id,
  title: cleanTitle(p.title),
  date: p.publishDate,
  labels: (p.labels || []).map((l) => l.name),
  images: (p.linkedIn?.assets || [])
    .filter((a) => (a.mimetype || '').startsWith('image/'))
    .map((a) => ({ asset: a.id, w: a.width, h: a.height })),
  copy: (p.linkedIn?.copy || '').trim(),
}));

console.log(`posts: ${posts.length} pulled from Ordinal`);

// --- 2. Analytics (permalink + engagement) --------------------------------
const linkedin = {
  _comment: [
    'Keyed by the Ordinal post id in posts.json. Source: Ordinal\'s LinkedIn',
    'post analytics endpoint, which carries the real LinkedIn permalink and',
    'the real engagement counts.',
    '',
    `Counts are a point-in-time reading captured on ${today()} and only move`,
    'when this file is refreshed, so treat them as \'at least this many\'.',
    'Posts with no entry render without a link or counts.',
    '',
    'urn is the tail of https://www.linkedin.com/feed/update/urn:li:<kind>:<id>.',
    'Regenerated by tools/sync-ordinal.mjs.',
  ],
};

let analytics = [];
try {
  const q = new URLSearchParams({ startDate: SINCE, endDate: new Date().toISOString() });
  const res = await api(`/analytics/linkedin/${LINKEDIN_PROFILE_ID}/posts?${q}`);
  analytics = Array.isArray(res) ? res : res.items || res.posts || [];
} catch (e) {
  console.error(`analytics fetch failed, writing posts without counts: ${e.message}`);
}

for (const row of analytics) {
  const id = row.ordinalPost?.id;
  if (!id) continue;
  const urn = extractUrn(row.url);
  if (!urn) continue; // build-notes needs a valid urn to render the link
  linkedin[id] = { urn, likes: row.likeCount || 0, comments: row.commentCount || 0 };
}
console.log(`analytics: ${Object.keys(linkedin).length - 1} posts matched a permalink`);

// --- 3. Images (download once) --------------------------------------------
if (!existsSync(IMG)) mkdirSync(IMG, { recursive: true });
let downloaded = 0;
for (const p of rawPosts) {
  for (const a of p.linkedIn?.assets || []) {
    if (!(a.mimetype || '').startsWith('image/')) continue;
    const out = resolve(IMG, `${a.id}.jpg`);
    if (existsSync(out)) continue;
    const res = await fetch(a.url, { headers: auth, redirect: 'follow' });
    if (!res.ok) {
      console.error(`  image ${a.id} -> ${res.status}, skipped`);
      continue;
    }
    writeFileSync(out, Buffer.from(await res.arrayBuffer()));
    downloaded++;
  }
}
console.log(`images: ${downloaded} downloaded`);

// --- 4. Write ---------------------------------------------------------------
writeJson(resolve(DATA, 'posts.json'), posts);
writeJson(resolve(DATA, 'linkedin.json'), linkedin);
console.log('wrote notes/_data/posts.json and linkedin.json');

// ---------------------------------------------------------------------------

function cleanTitle(t = '') {
  // Ordinal titles are internal working names; strip a trailing parenthetical
  // ("The Smallest Yes (offer front door)" -> "The Smallest Yes"). Title is
  // only used in JSON-LD headline, never shown to readers.
  return t.replace(/\s*\([^)]*\)\s*$/, '').trim();
}

function extractUrn(url = '') {
  // Want "<kind>:<id>", e.g. share:7494055239222870016, from a LinkedIn URL.
  let m = url.match(/urn:li:(\w+):(\d+)/i);
  if (m) return `${m[1]}:${m[2]}`;
  m = url.match(/-(activity|share|ugcPost)-(\d+)/i);
  if (m) return `${m[1]}:${m[2]}`;
  m = url.match(/(activity|share|ugcPost)[:\-](\d{15,})/i);
  if (m) return `${m[1]}:${m[2]}`;
  return null;
}

function today() {
  return new Date().toISOString().slice(0, 10);
}

function writeJson(path, value) {
  writeFileSync(path, JSON.stringify(value, null, 2) + '\n');
}
